"""Specialized Agent implementations for the Multi-Agent Research Assistant.

LangGraph Concept: Specialized Agent Nodes
------------------------------------------
In LangGraph, each agent is a Python function (node) that receives the current
`ResearchState` and returns a dictionary of state updates.

Rather than relying on a single monolithic LLM call:
1. Planning Agent decomposes the user's question into targeted sub-tasks.
2. DuckDuckGo Agent queries live web search tools via MCP.
3. Wikipedia Agent queries encyclopedic tools via MCP in parallel.
4. Summarizer Agent synthesizes and contrasts evidence across sources.
5. Final Answer Agent compiles a cited, verified final response.
"""

import asyncio
import json
import logging
import os
from pathlib import Path
import re
from typing import Any

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import BaseTool
from langgraph.types import interrupt

from app.state import ResearchState, merge_search_results
from app.tools import (
    async_duckduckgo_search,
    async_wikipedia_search,
    load_research_tools,
)

# Environment loading: loads .env (best practice), with fallback to .env.example
_project_root = Path(__file__).resolve().parent.parent
_env_path = _project_root / ".env"
_example_path = _project_root / ".env.example"

if _env_path.exists():
    load_dotenv(dotenv_path=_env_path, override=True)
else:
    load_dotenv(override=True)

# Seamless fallback if user adds their key directly into .env.example
if _example_path.exists():
    provider = os.getenv("LLM_PROVIDER", "mistral").lower()
    key_var = "MISTRAL_API_KEY" if provider == "mistral" else ("GOOGLE_API_KEY" if provider == "gemini" else "GROQ_API_KEY")
    val = os.getenv(key_var, "")
    if not val or "your_" in val:
        load_dotenv(dotenv_path=_example_path, override=True)

logger = logging.getLogger("research_assistant.agents")


# ---------------------------------------------------------------------------
# Structured Output Schemas
# ---------------------------------------------------------------------------
class ResearchPlanOutput(BaseModel):
    """Structured research plan generated by the Planning Agent."""

    research_plan: list[str] = Field(
        description="A list of 3 to 5 specific, distinct search tasks or queries to research the question."
    )


# ---------------------------------------------------------------------------
# LLM Provider Factory
# ---------------------------------------------------------------------------
def get_llm():
    """Initialize and return the configured LangChain ChatModel.

    Checks `LLM_PROVIDER` in environment:
    - 'gemini' (default): Uses `langchain-google-genai` ChatGoogleGenerativeAI.
    - 'groq': Uses ChatGroq if installed and configured.
    - 'mistral': Uses ChatMistralAI if installed and configured.
    - If no valid API key is present or LLM_PROVIDER is 'mock', returns None
      to enable graceful heuristic fallback for offline testing.
    """
    provider = os.getenv("LLM_PROVIDER", "gemini").lower()
    google_key = os.getenv("GOOGLE_API_KEY", "")

    if provider == "gemini":
        if not google_key or "your_api_key_here" in google_key:
            logger.info("No active GOOGLE_API_KEY found; operating in graceful mock/offline mode.")
            return None
        from langchain_google_genai import ChatGoogleGenerativeAI

        model_name = os.getenv("GEMINI_MODEL", "gemini-3.6-flash")
        return ChatGoogleGenerativeAI(
            model=model_name,
            google_api_key=google_key,
            temperature=0.2,
        )

    if provider == "groq":
        groq_key = os.getenv("GROQ_API_KEY", "")
        if not groq_key or "your_api_key_here" in groq_key:
            return None
        try:
            from langchain_groq import ChatGroq

            return ChatGroq(
                model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
                api_key=groq_key,
                temperature=0.2,
            )
        except ImportError:
            logger.warning("langchain-groq not installed. Falling back to offline mode.")
            return None

    if provider == "mistral":
        mistral_key = os.getenv("MISTRAL_API_KEY", "")
        if not mistral_key or "your_api_key_here" in mistral_key:
            logger.info("No active MISTRAL_API_KEY found; operating in graceful mock/offline mode.")
            return None
        try:
            from langchain_mistralai import ChatMistralAI

            model_name = os.getenv("MISTRAL_MODEL", "open-mistral-7b")
            return ChatMistralAI(
                model=model_name,
                mistral_api_key=mistral_key,
                temperature=0.2,
                timeout=20,
                max_retries=2,
            )
        except ImportError:
            logger.warning("langchain-mistralai not installed. Falling back to offline mode.")
            return None

    return None


# ---------------------------------------------------------------------------
# 1. Planning Agent
# ---------------------------------------------------------------------------
async def planning_agent(state: ResearchState) -> dict[str, Any]:
    """Analyze the user question and produce a structured research plan.

    LangGraph Concept: Planning Node
    - Receives `question` from state.
    - Uses structured LLM output to produce 3-5 specific sub-queries.
    - Updates `state['research_plan']`.
    """
    question = state.get("question", "").strip()
    logger.info(f"[Planner] Creating research plan for: '{question}'")

    llm = get_llm()
    plan: list[str] = []

    if llm is not None:
        try:
            # Try structured output first
            structured_llm = llm.with_structured_output(ResearchPlanOutput)
            prompt = (
                f"You are an expert research planner. Deconstruct the following question "
                f"into 3 to 4 distinct, highly focused research tasks or search queries that "
                f"cover definitions, core mechanisms, benefits/trade-offs, and practical comparisons.\n\n"
                f"Question: {question}"
            )
            result = await structured_llm.ainvoke(prompt)
            if result and getattr(result, "research_plan", None):
                plan = [p.strip() for p in result.research_plan if p.strip()]
        except Exception as exc:
            logger.warning(f"[Planner] Structured LLM call failed: {exc}. Trying raw completion.")
            try:
                raw_res = await llm.ainvoke(
                    f"Create a 3-point research plan for: '{question}'. "
                    f"Return ONLY a JSON list of strings, for example: [\"query 1\", \"query 2\", \"query 3\"]"
                )
                content = raw_res.content if hasattr(raw_res, "content") else str(raw_res)
                # Extract json list
                match = re.search(r"\[.*\]", content, re.DOTALL)
                if match:
                    plan = json.loads(match.group(0))
            except Exception as raw_exc:
                logger.warning(f"[Planner] Raw completion also failed: {raw_exc}.")

    # Deterministic fallback plan if LLM not configured or offline
    if not plan:
        plan = [
            f"Overview and definition of {question}",
            f"Key features and technical architecture of {question}",
            f"Advantages, limitations, and use cases of {question}",
        ]

    logger.info(f"[Planner] Generated {len(plan)} research tasks: {plan}")
    return {"research_plan": plan}


def parse_mcp_content(raw_value: Any, query: str) -> list[dict[str, Any]]:
    """Parse MCP tool result into structured dictionary records."""
    records: list[dict[str, Any]] = []

    def _process_text(text: str):
        try:
            parsed = json.loads(text)
            if isinstance(parsed, list):
                for p in parsed:
                    if isinstance(p, dict):
                        records.append({"query": query, **p})
                    else:
                        records.append({"query": query, "content": str(p)})
            elif isinstance(parsed, dict):
                records.append({"query": query, **parsed})
            else:
                records.append({"query": query, "content": str(parsed)})
        except Exception:
            records.append({"query": query, "content": text})

    if isinstance(raw_value, list):
        for item in raw_value:
            if isinstance(item, dict):
                if "text" in item:
                    _process_text(item["text"])
                else:
                    records.append({"query": query, **item})
            elif hasattr(item, "text"):
                _process_text(getattr(item, "text", ""))
            elif isinstance(item, str):
                _process_text(item)
    elif isinstance(raw_value, dict):
        if "text" in raw_value:
            _process_text(raw_value["text"])
        else:
            records.append({"query": query, **raw_value})
    elif isinstance(raw_value, str):
        _process_text(raw_value)

    return records


# ---------------------------------------------------------------------------
# 2. DuckDuckGo Retrieval Agent
# ---------------------------------------------------------------------------
async def duckduckgo_retrieval_agent(state: ResearchState) -> dict[str, Any]:
    """Execute live web searches using DuckDuckGo MCP tool based on research plan.

    LangGraph Concept: Specialized Retrieval Node (Branch 1)
    - Reads `research_plan` and `retry_count`.
    - Selects targeted web search queries.
    - Invokes the MCP tool asynchronously.
    - Normalizes results into consistent schema: {source, query, title, url, content}.
    """
    plan = state.get("research_plan", [])
    question = state.get("question", "")
    retry_count = state.get("retry_count", 0)

    logger.info("[GRAPH] Subgraph started")
    logger.info(f"[DuckDuckGo] Searching live web (attempt {retry_count + 1})...")

    # Select queries: adapt if this is a retry attempt
    queries_to_run: list[str] = []
    if retry_count > 0:
        # Broaden search on retry
        queries_to_run = [f"{question} overview summary", f"{question} documentation"]
    elif plan:
        # Pick top 2 queries from plan
        queries_to_run = plan[:2]
    else:
        queries_to_run = [question]

    raw_items: list[dict[str, Any]] = []
    errors: list[str] = []

    try:
        tools = await load_research_tools()
        ddg_tool: BaseTool | None = tools.get("duckduckgo")

        if ddg_tool is not None:
            for q in queries_to_run:
                try:
                    logger.debug(f"[DuckDuckGo] Invoking MCP tool for query: '{q}'")
                    result = await ddg_tool.ainvoke({"query": q, "max_results": 3})
                    parsed_records = parse_mcp_content(result, q)
                    raw_items.extend(parsed_records)
                except Exception as tool_exc:
                    err_msg = f"DuckDuckGo MCP tool query '{q}' failed: {tool_exc}"
                    logger.warning(f"[DuckDuckGo] {err_msg}")
                    errors.append(err_msg)
        else:
            errors.append("DuckDuckGo MCP tool was not found in loaded tools.")
    except Exception as mcp_exc:
        err_msg = f"Failed to connect to DuckDuckGo MCP server: {mcp_exc}"
        logger.error(f"[DuckDuckGo] {err_msg}")
        errors.append(err_msg)

    # Normalize results into expected schema
    normalized_results: list[dict[str, str]] = []
    for item in raw_items:
        title = item.get("title") or "Web Search Result"
        content = item.get("content") or item.get("body") or ""
        url = item.get("url") or item.get("href") or ""
        q = item.get("query") or question

        if content.strip():
            normalized_results.append(
                {
                    "source": "duckduckgo",
                    "query": q,
                    "title": title,
                    "url": url,
                    "content": content,
                }
            )

    logger.info(f"[DuckDuckGo] Retrieved {len(normalized_results)} valid records.")
    return {
        "duckduckgo_results": normalized_results,
        "search_results": normalized_results,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# 3. Wikipedia Retrieval Agent
# ---------------------------------------------------------------------------
async def wikipedia_retrieval_agent(state: ResearchState) -> dict[str, Any]:
    """Retrieve encyclopedia articles using Wikipedia MCP tool based on research plan.

    LangGraph Concept: Specialized Retrieval Node (Branch 2)
    - Runs in parallel with DuckDuckGo agent.
    - Queries Wikipedia MCP tool for conceptual / background articles.
    - Normalizes results into consistent schema: {source, query, title, url, content}.
    """
    plan = state.get("research_plan", [])
    question = state.get("question", "")
    retry_count = state.get("retry_count", 0)

    logger.info(f"[Wikipedia] Searching encyclopedia (attempt {retry_count + 1})...")

    # Select queries: adapt on retry or extract core concept
    queries_to_run: list[str] = []
    if retry_count > 0:
        # Simplify to base keywords on retry
        cleaned = re.sub(r"(?i)\b(what|how|why|is|are|the|of|for|in|to)\b", "", question).strip()
        queries_to_run = [cleaned if cleaned else question]
    elif len(plan) >= 2:
        # Pick 2 complementary queries from plan
        queries_to_run = [plan[0], plan[-1]]
    elif plan:
        queries_to_run = [plan[0]]
    else:
        queries_to_run = [question]

    raw_items: list[dict[str, Any]] = []
    errors: list[str] = []

    try:
        tools = await load_research_tools()
        wiki_tool: BaseTool | None = tools.get("wikipedia")

        if wiki_tool is not None:
            for q in queries_to_run:
                try:
                    logger.debug(f"[Wikipedia] Invoking MCP tool for query: '{q}'")
                    result = await wiki_tool.ainvoke({"query": q, "max_results": 2})
                    parsed_records = parse_mcp_content(result, q)
                    raw_items.extend(parsed_records)
                except Exception as tool_exc:
                    err_msg = f"Wikipedia MCP tool query '{q}' failed: {tool_exc}"
                    logger.warning(f"[Wikipedia] {err_msg}")
                    errors.append(err_msg)
        else:
            errors.append("Wikipedia MCP tool was not found in loaded tools.")
    except Exception as mcp_exc:
        err_msg = f"Failed to connect to Wikipedia MCP server: {mcp_exc}"
        logger.error(f"[Wikipedia] {err_msg}")
        errors.append(err_msg)

    # Normalize results into expected schema
    normalized_results: list[dict[str, str]] = []
    for item in raw_items:
        title = item.get("title") or "Wikipedia Article"
        content = item.get("content") or item.get("summary") or ""
        url = item.get("url") or ""
        q = item.get("query") or question

        if content.strip():
            normalized_results.append(
                {
                    "source": "wikipedia",
                    "query": q,
                    "title": title,
                    "url": url,
                    "content": content,
                }
            )

    logger.info(f"[Wikipedia] Retrieved {len(normalized_results)} valid records.")
    return {
        "wikipedia_results": normalized_results,
        "search_results": normalized_results,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# 4. Evaluation & Retry Node (Fan-in Join Point)
# ---------------------------------------------------------------------------
async def evaluate_retrieval(state: ResearchState) -> dict[str, Any]:
    """Examine retrieved results and manage retry state if needed.

    LangGraph Concept: Fan-in Barrier & Conditional Transition
    - Both parallel branches (DuckDuckGo and Wikipedia) merge into this node.
    - Determines if useful content has been collected.
    - If empty and retry budget remains, increments `retry_count`.
    """
    search_results = state.get("search_results", [])
    retry_count = state.get("retry_count", 0)

    # Filter out empty or error results to determine true content availability
    valid_results = [
        r for r in search_results
        if r.get("content") and not r.get("title", "").lower().startswith("search error")
    ]

    has_results = len(valid_results) > 0
    max_retries = int(os.getenv("MAX_RETRIES", "2"))

    if not has_results and retry_count < max_retries:
        next_retry = retry_count + 1
        logger.warning(
            f"[Retry Check] No search results found. Scheduling retry {next_retry}/{max_retries}..."
        )
        return {"retry_count": next_retry}

    if not has_results and retry_count >= max_retries:
        logger.warning(
            f"[Retry Check] Maximum retry limit ({max_retries}) reached. Continuing with available context."
        )

    logger.info(f"[Retry Check] Found {len(valid_results)} usable records. Proceeding to summarizer.")
    return {}


# ---------------------------------------------------------------------------
# 5. Summarization Agent
# ---------------------------------------------------------------------------
async def summarization_agent(state: ResearchState) -> dict[str, Any]:
    """Consolidate research findings, deduplicate, and identify key facts.

    LangGraph Concept: Synthesis Node
    - Combines information from DuckDuckGo (live web) and Wikipedia (encyclopedic).
    - Avoids hallucination by grounding only on retrieved results.
    - Stores synthesized summary in `state['summary']`.
    """
    question = state.get("question", "")
    research_plan = state.get("research_plan", [])
    search_results = state.get("search_results", [])

    logger.info("[Summarizer] Combining research and synthesizing summary...")

    valid_results = [
        r for r in search_results
        if r.get("content") and not r.get("title", "").lower().startswith("search error")
    ]

    if not valid_results:
        fallback_summary = (
            f"No live research results were retrieved for '{question}'. "
            f"The search queries in the research plan ({', '.join(research_plan)}) "
            f"did not return accessible documents through DuckDuckGo or Wikipedia."
        )
        return {"summary": fallback_summary}

    # Format documents for synthesis
    formatted_docs: list[str] = []
    for idx, doc in enumerate(valid_results, 1):
        source = doc.get("source", "unknown").upper()
        title = doc.get("title", "Untitled")
        url = doc.get("url", "No URL")
        snippet = doc.get("content", "").strip()[:800]
        formatted_docs.append(
            f"[{idx}] Source: {source} | Title: {title} | Link: {url}\nExcerpt: {snippet}\n"
        )
    evidence_text = "\n".join(formatted_docs)

    llm = get_llm()
    summary_text = ""

    if llm is not None:
        system_prompt = (
            "You are a meticulous research analyst. Your job is to summarize retrieved research findings.\n"
            "Rules:\n"
            "1. Combine information from DuckDuckGo and Wikipedia.\n"
            "2. Eliminate duplicate facts and contradictions.\n"
            "3. Clearly cite which facts come from DuckDuckGo (web) vs Wikipedia.\n"
            "4. Do NOT hallucinate or extrapolate facts not present in the evidence.\n"
            "5. Keep the summary structured and concise."
        )
        user_prompt = (
            f"Question: {question}\n\n"
            f"Research Plan Tasks: {json.dumps(research_plan)}\n\n"
            f"Retrieved Evidence:\n{evidence_text}\n\n"
            f"Produce a comprehensive synthesis and summary."
        )
        try:
            res = await llm.ainvoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
            summary_text = res.content if hasattr(res, "content") else str(res)
        except Exception as exc:
            logger.warning(f"[Summarizer] LLM invocation failed: {exc}. Using heuristic summary.")

    # Fallback heuristic summarization if LLM is offline or errored
    if not summary_text:
        ddg_count = sum(1 for r in valid_results if r.get("source") == "duckduckgo")
        wiki_count = sum(1 for r in valid_results if r.get("source") == "wikipedia")
        highlights = [
            f"- **{r.get('title')}** ({r.get('source')}): {r.get('content', '')[:180]}..."
            for r in valid_results[:4]
        ]
        summary_text = (
            f"### Research Synthesis for: '{question}'\n\n"
            f"Synthesized evidence from {ddg_count} DuckDuckGo web results and {wiki_count} Wikipedia articles.\n\n"
            f"**Key Findings Identified:**\n"
            + "\n".join(highlights)
        )

    logger.info("[Summarizer] Research summary generated successfully.")
    return {"summary": summary_text}


# ---------------------------------------------------------------------------
# 6. Final Answer Agent
# ---------------------------------------------------------------------------
async def final_answer_agent(state: ResearchState) -> dict[str, Any]:
    """Generate user-facing answer with Answer, Key Findings, and Sources.

    LangGraph Concept: Final Presentation Node
    - Receives `summary` and `search_results`.
    - Answers only from research gathered by prior nodes.
    - Formats output with strict sections: Answer, Key Findings, Sources.
    """
    question = state.get("question", "")
    summary = state.get("summary", "")
    search_results = state.get("search_results", [])

    logger.info("[Final Answer] Generating response with sources...")

    # Extract distinct source URLs and titles
    distinct_sources: list[tuple[str, str, str]] = []
    seen_urls: set[str] = set()
    for r in search_results:
        url = r.get("url", "").strip()
        title = r.get("title", "").strip()
        source = r.get("source", "").capitalize()
        if url and url not in seen_urls and not title.lower().startswith("search error"):
            seen_urls.add(url)
            distinct_sources.append((source, title, url))

    llm = get_llm()
    answer_text = ""
    human_feedback = state.get("human_feedback")

    if llm is not None:
        sources_list_str = "\n".join(f"- [{title}]({url}) ({source})" for source, title, url in distinct_sources)
        system_prompt = (
            "You are a professional research assistant. Formulate the final answer for the user.\n"
            "Structure your response strictly as follows:\n\n"
            "## Answer\n"
            "<A clear, comprehensive direct answer to the user's question, grounded in the research summary and any incorporated reviewer feedback.>\n\n"
            "## Key Findings\n"
            "<Bullet points highlighting 3-5 critical takeaways, advantages, or trade-offs.>\n\n"
            "## Sources\n"
            "<List of markdown links to all sources referenced with their titles.>\n\n"
            "Never invent facts or references not provided in the summary."
        )
        feedback_clause = f"\nHuman Reviewer Feedback Addressed: \"{human_feedback}\"\n" if human_feedback else ""
        user_prompt = (
            f"User Question: {question}\n"
            f"{feedback_clause}\n"
            f"Research Summary:\n{summary}\n\n"
            f"Available Sources:\n{sources_list_str}"
        )
        try:
            res = await llm.ainvoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
            answer_text = res.content if hasattr(res, "content") else str(res)
        except Exception as exc:
            logger.warning(f"[Final Answer] LLM call failed: {exc}. Using template.")

    # Fallback template formatting
    if not answer_text:
        source_lines = [
            f"- [{title}]({url}) ({source})" for source, title, url in distinct_sources
        ] or ["- No external source links accessible."]

        feedback_bullet = f"\n- Incorporated human reviewer feedback: '{human_feedback}'." if human_feedback else ""
        answer_text = (
            f"## Answer\n"
            f"Based on gathered research for '{question}':\n\n"
            f"{summary}\n\n"
            f"## Key Findings\n"
            f"- Information was gathered independently from live web search and encyclopedic records.\n"
            f"- The synthesis consolidates definitions, core components, and practical context.{feedback_bullet}\n"
            f"- Further domain-specific verification may be conducted via the sources below.\n\n"
            f"## Sources\n"
            + "\n".join(source_lines)
        )

    logger.info("[Final Answer] Final response compiled.")
    return {"final_answer": answer_text}


# ---------------------------------------------------------------------------
# 7. Human-in-the-Loop Approval Node
# ---------------------------------------------------------------------------
async def human_approval_node(state: ResearchState) -> dict[str, Any]:
    """Human-in-the-Loop decision gate.

    LangGraph Concept: Dynamic Interrupt
    - Pauses graph execution using `interrupt()`.
    - Passes structured payload containing summary, question, and result to caller.
    - Graph execution suspends until resumed with Command(resume=...).
    - Updates state with approval decision and optional revision feedback.
    """
    summary = state.get("summary", "")
    question = state.get("question", "")

    logger.info("[GRAPH] Waiting for human approval")
    response = interrupt(
        {
            "type": "approval",
            "message": "Please review the generated research summary.",
            "data": {
                "result": summary,
                "summary": summary,
                "question": question,
            },
        }
    )

    if isinstance(response, dict):
        approved = bool(response.get("approved", False))
        feedback = response.get("feedback")
    else:
        approved = bool(response)
        feedback = None

    if approved:
        logger.info("[GRAPH] Human approved")
    else:
        logger.info("[GRAPH] Human rejected result")
        if feedback:
            logger.info(f"[GRAPH] Human feedback received: {feedback}")

    return {
        "human_approved": approved,
        "human_feedback": feedback,
    }


# ---------------------------------------------------------------------------
# 8. Revision Agent & Heuristic Rework Engine
# ---------------------------------------------------------------------------
def clean_summary_sections(text: str, headers_to_remove: list[str]) -> str:
    """Remove specific markdown section headers and old revision summaries to prevent duplication."""
    text = re.split(r"\*\*\[Revision (?:Summary|Applied)\]\*\*.*", text, flags=re.DOTALL)[0].strip()
    for header in headers_to_remove:
        pattern = r"(?m)^### " + re.escape(header) + r".*?(?=(?:^### |\Z))"
        text = re.sub(pattern, "", text, flags=re.DOTALL).strip()
    return text


async def perform_supplementary_retrieval(
    question: str,
    feedback: str,
) -> list[dict[str, Any]]:
    """Retrieve targeted evidence to satisfy human reviewer feedback.

    LangGraph Concept: Dynamic Feedback-Driven Retrieval
    - Extracts core search terms from reviewer feedback and original inquiry.
    - Queries DuckDuckGo and Wikipedia tools for new, relevant documents.
    - Returns normalized list of search result records.
    """
    if not feedback or not feedback.strip():
        return []

    fb = feedback.strip()
    fb_lower = fb.lower()

    # If feedback is purely about length/formatting without asking for new topics, skip search
    is_pure_formatting = any(
        w in fb_lower
        for w in [
            "shorter", "tldr", "tl;dr", "few lines", "quick answer", "condense",
            "summarize briefly", "make it short", "too long",
        ]
    ) and not any(
        kw in fb_lower
        for kw in ["add", "include", "explain", "about", "what", "how", "why", "who", "versus", "vs", "support", "war", "policy", "detail", "more"]
    )
    if is_pure_formatting:
        return []

    # Clean feedback to isolate the core requested subject or topic
    clean_topic = re.sub(
        r"(?i)^(please\s+)?(can you\s+)?(could you\s+)?(add|include|provide|give|tell me about|explain|focus on|expand on|elaborate on|what about|write about|bring in)\s+(the\s+|more\s+|some\s+)?(information about|details about|info on|details on|data on)?",
        "",
        fb,
    ).strip(" .?!,;:")

    # Clean question to extract primary subject
    clean_subject = re.sub(
        r"(?i)^(who|what|where|when|why|how)\s+(is|was|are|were|do|does|did)\s+(the\s+)?",
        "",
        question.strip(" ?."),
    ).strip()

    # Formulate complementary queries
    queries_to_run: list[str] = []
    if clean_subject and clean_subject.lower() not in clean_topic.lower():
        queries_to_run.append(f"{clean_subject} {clean_topic}".strip())

    if clean_topic:
        queries_to_run.append(clean_topic)
    else:
        queries_to_run.append(f"{clean_subject} {fb}".strip())

    # Deduplicate queries preserving order, limit to top 2
    seen_q = set()
    unique_queries: list[str] = []
    for q in queries_to_run:
        q_norm = q.lower().strip()
        if q_norm and q_norm not in seen_q:
            seen_q.add(q_norm)
            unique_queries.append(q.strip())
    unique_queries = unique_queries[:2]

    logger.info(f"[Revision Retrieval] Formulated targeted feedback queries: {unique_queries}")

    raw_items: list[dict[str, Any]] = []

    # 1. Try MCP tools first with a strict timeout
    try:
        tools = await asyncio.wait_for(load_research_tools(), timeout=3.0)
        ddg_tool: BaseTool | None = tools.get("duckduckgo")
        wiki_tool: BaseTool | None = tools.get("wikipedia")

        for q in unique_queries:
            if ddg_tool is not None:
                try:
                    res = await asyncio.wait_for(ddg_tool.ainvoke({"query": q, "max_results": 3}), timeout=4.0)
                    parsed = parse_mcp_content(res, q)
                    for item in parsed:
                        item.setdefault("source", "duckduckgo")
                    raw_items.extend(parsed)
                except Exception as exc:
                    logger.debug(f"[Revision Retrieval] MCP DuckDuckGo query '{q}' error: {exc}")

            if wiki_tool is not None:
                try:
                    res = await asyncio.wait_for(wiki_tool.ainvoke({"query": q, "max_results": 2}), timeout=4.0)
                    parsed = parse_mcp_content(res, q)
                    for item in parsed:
                        item.setdefault("source", "wikipedia")
                    raw_items.extend(parsed)
                except Exception as exc:
                    logger.debug(f"[Revision Retrieval] MCP Wikipedia query '{q}' error: {exc}")
    except Exception as exc:
        logger.debug(f"[Revision Retrieval] MCP tools loading bypassed or failed: {exc}")

    # 2. If MCP tools returned no usable records, use direct search helpers
    usable_mcp = [r for r in raw_items if r.get("content") and not r.get("title", "").lower().startswith("search error")]
    if not usable_mcp:
        for q in unique_queries:
            try:
                ddg_records = await asyncio.wait_for(async_duckduckgo_search(q, max_results=3), timeout=5.0)
                for item in ddg_records:
                    item["query"] = q
                raw_items.extend(ddg_records)
            except Exception as exc:
                logger.debug(f"[Revision Retrieval] Direct DuckDuckGo failed for '{q}': {exc}")

            try:
                wiki_records = await asyncio.wait_for(async_wikipedia_search(q, max_results=2), timeout=5.0)
                for item in wiki_records:
                    item["query"] = q
                raw_items.extend(wiki_records)
            except Exception as exc:
                logger.debug(f"[Revision Retrieval] Direct Wikipedia failed for '{q}': {exc}")

    # 3. Normalize into standard search result schema
    normalized_results: list[dict[str, str]] = []
    seen_urls: set[str] = set()
    for item in raw_items:
        title = item.get("title") or "Feedback Search Result"
        content = item.get("content") or item.get("body") or ""
        url = item.get("url") or item.get("href") or ""
        src = item.get("source") or "web"
        q = item.get("query") or feedback

        if not content.strip() or title.lower().startswith("search error") or title.lower().startswith("wikipedia error"):
            continue

        dedup_key = (url or title).strip().lower()
        if dedup_key in seen_urls:
            continue
        seen_urls.add(dedup_key)

        normalized_results.append(
            {
                "source": src,
                "query": q,
                "title": title,
                "url": url,
                "content": content,
            }
        )

    logger.info(f"[Revision Retrieval] Gathered {len(normalized_results)} targeted evidence records for feedback.")
    return normalized_results


def heuristic_rework_summary(
    question: str,
    summary: str,
    feedback: str,
    search_results: list[dict],
    new_results: list[dict] | None = None,
) -> str:
    """Intelligently rework the research summary to fulfill human reviewer feedback.

    Dynamically analyzes reviewer intent (examples, short answer, technical depth, comparisons,
    or targeted topic expansion) and incorporates retrieved evidence tailored strictly to the
    feedback and question.
    """
    fb_lower = feedback.lower()

    # Filter usable search results
    valid_results = [
        r
        for r in search_results
        if r.get("content")
        and not r.get("title", "").lower().startswith("search error")
    ]

    # Clean existing revision sections to prevent duplication across multiple rounds
    clean_summary = clean_summary_sections(
        summary,
        [
            f"Concise Research Summary for: '{question}'",
            f"Concrete Practical Examples & Use Cases for '{question}'",
            f"In-Depth Technical Architecture & Mechanics for: '{question}'",
            f"Comparative Analysis & Trade-Offs for: '{question}'",
            f"Refined Analysis & Additional Findings for: '{question}'",
            "Supplementary Analysis & Findings",
        ],
    )
    clean_summary = re.sub(
        r"(?m)^### (?:Concise Research Summary|Concrete Practical Examples|In-Depth Technical|Comparative Analysis|Refined Analysis|Supplementary Analysis).*?(?=(?:^### |\Z))",
        "",
        clean_summary,
        flags=re.DOTALL,
    ).strip()

    # 1. User requested a short, concise, or brief answer
    is_short_request = any(
        w in fb_lower
        for w in [
            "short",
            "brief",
            "concise",
            "shorter",
            "tldr",
            "tl;dr",
            "few lines",
            "quick answer",
            "simple",
            "condense",
            "summarize briefly",
        ]
    )
    if is_short_request and not any(w in fb_lower for w in ["add", "include", "more", "explain"]):
        base_lines = [line.strip() for line in summary.split("\n") if line.strip()]
        highlights = [l for l in base_lines if l.startswith("-") or l.startswith("1.") or l.startswith("2.")][:3]
        if not highlights:
            highlights = [f"- {l}" for l in base_lines if len(l) > 30 and not l.startswith("#")][:3]
        short_bullets = "\n".join(highlights) if highlights else f"- Core findings synthesized from research for '{question}'."
        return (
            f"### Concise Research Summary for: '{question}'\n\n"
            f"**Core Findings:**\n{short_bullets}\n\n"
            f"**[Revision Summary]**: Condensed summary to fulfill reviewer request: *\"{feedback}\"*"
        )

    # 2. User requested practical examples or use cases
    count_match = re.search(r"(\d+)\s*(?:more\s*)?examples?", fb_lower)
    if not count_match:
        count_match = re.search(r"total\s*(\d+)", fb_lower)
    if not count_match:
        count_match = re.search(r"(\d+)\s*(?:distinct\s*)?examples?", fb_lower)

    example_count = int(count_match.group(1)) if count_match else None
    is_example_feedback = any(
        w in fb_lower
        for w in [
            "example",
            "use case",
            "sample",
            "walkthrough",
            "demo",
            "instance",
            "practical",
            "scenario",
            "how to",
            "case study",
        ]
    )

    if is_example_feedback or example_count is not None:
        target_count = example_count if example_count else (6 if "example 1" in summary.lower() else 3)
        target_count = max(1, min(target_count, 10))

        example_lines = [
            f"### Concrete Practical Examples & Use Cases for '{question}' ({target_count} Examples)\n",
            f"To address the request for practical examples illustrating **'{question}'**, here are real-world applications derived directly from the research:\n",
        ]

        pool = new_results if (new_results and len(new_results) > 0) else valid_results
        if pool:
            for idx in range(1, target_count + 1):
                doc = pool[(idx - 1) % len(pool)]
                title = doc.get("title", f"Scenario {idx}").strip()
                source = doc.get("source", "web").upper()
                snippet = doc.get("content", "").strip()[:240].replace("\n", " ")
                url = doc.get("url", "")
                link_str = f" | [Source Link]({url})" if url and url.startswith("http") else ""

                example_lines.append(f"{idx}. **{title}** ({source}{link_str})")
                example_lines.append(f"   - **Context**: Real-world application addressing '{question}'.")
                example_lines.append(f"   - **Demonstrated Workflow**: {snippet}...\n")
        else:
            for idx in range(1, target_count + 1):
                example_lines.append(f"{idx}. **Practical Application Scenario {idx} for '{question}'**")
                example_lines.append(f"   - **Context**: Domain implementation scenario {idx}.")
                example_lines.append(f"   - **Application**: Executing practical methods addressing '{question}'.\n")

        expanded_section = "\n".join(example_lines)

    # 3. User requested technical depth, architecture, or mechanisms
    elif any(
        w in fb_lower
        for w in [
            "technical",
            "architecture",
            "mechanism",
            "process",
            "how it works",
            "deep",
            "depth",
            "framework",
        ]
    ):
        tech_points = []
        pool = new_results if (new_results and len(new_results) > 0) else valid_results
        for r in pool[:4]:
            t = r.get("title", "Technical Finding")
            c = r.get("content", "").strip()[:200].replace("\n", " ")
            tech_points.append(f"- **{t}**: {c}...")

        tech_text = "\n".join(tech_points) if tech_points else f"- Core operational mechanisms and architecture relevant to '{question}'."
        expanded_section = (
            f"### In-Depth Technical Architecture & Mechanics for: '{question}'\n\n"
            f"To address reviewer feedback regarding technical depth and mechanisms:\n\n"
            f"{tech_text}\n"
        )

    # 4. User requested comparisons or trade-offs
    elif any(
        w in fb_lower
        for w in [
            "compare",
            "comparison",
            "versus",
            "vs",
            "tradeoff",
            "trade-off",
            "difference",
            "benefit",
            "pros",
            "cons",
        ]
    ):
        pool = new_results if (new_results and len(new_results) > 1) else valid_results
        doc_a = pool[0].get("title", "Primary Approach") if len(pool) > 0 else "Primary Approach"
        doc_b = pool[1].get("title", "Alternative Method") if len(pool) > 1 else "Alternative Method"
        expanded_section = (
            f"### Comparative Analysis & Trade-Offs for: '{question}'\n\n"
            f"| Evaluation Dimension | {doc_a[:35]} | {doc_b[:35]} |\n"
            f"|---|---|---|\n"
            f"| **Core Focus** | Primary implementation for '{question}' | Alternative perspective / baseline method |\n"
            f"| **Key Advantage** | High relevance and immediate applicability | Established reference framework |\n"
            f"| **Trade-Off** | Requires up-to-date validation | May lack contemporary nuances |\n"
        )

    # 5. Targeted topic / content feedback (e.g., adding specific aspects, policy stances, developments)
    else:
        # Prioritize records from new_results or records with keywords matching feedback
        feedback_words = set(re.findall(r"\b\w{3,}\b", fb_lower)) - {
            "please", "could", "would", "about", "provide", "include", "more", "some",
            "detail", "details", "information", "info", "give", "tell", "what", "with"
        }

        def _doc_match_score(doc: dict) -> int:
            score = 0
            text = (doc.get("title", "") + " " + doc.get("content", "") + " " + doc.get("query", "")).lower()
            for kw in feedback_words:
                if kw in text:
                    score += 1
            return score

        prioritized_pool: list[dict] = []
        if new_results:
            prioritized_pool.extend([r for r in new_results if r.get("content") and not r.get("title", "").lower().startswith("search error")])

        remaining = [r for r in valid_results if r not in prioritized_pool]
        remaining_sorted = sorted(remaining, key=_doc_match_score, reverse=True)
        prioritized_pool.extend(remaining_sorted)

        evidence_excerpts = []
        for r in prioritized_pool[:4]:
            t = r.get("title", "Evidence Record")
            c = r.get("content", "").strip()[:240].replace("\n", " ")
            src = r.get("source", "source").upper()
            url = r.get("url", "")
            link_str = f" | [Source Link]({url})" if url and url.startswith("http") else ""
            evidence_excerpts.append(f"- **{t}** ({src}{link_str}): {c}...")

        evidence_str = "\n".join(evidence_excerpts) if evidence_excerpts else f"- Cross-referenced gathered evidence addressing '{feedback}' for '{question}'."

        clean_topic_hdr = re.sub(
            r"(?i)^(please\s+)?(can you\s+)?(add|include|provide|give|tell me about|explain|focus on|expand on|elaborate on|what about|write about)\s+(the\s+|more\s+|some\s+)?(information about|details about|info on|details on|data on)?",
            "",
            feedback.strip(),
        ).strip(" .?!,;:")
        topic_title = clean_topic_hdr.title() if clean_topic_hdr else question

        expanded_section = (
            f"### Supplementary Analysis & Findings: {topic_title}\n\n"
            f"Addressing reviewer feedback: *\"{feedback}\"*\n\n"
            f"**Key Evidence & Developments:**\n{evidence_str}\n\n"
            f"**Core Synthesis:**\n"
            f"Based on targeted research regarding *\"{feedback}\"*, the gathered evidence directly addresses "
            f"the requested dimensions for **'{question}'**, incorporating specific policy developments, contemporary "
            f"facts, and verified context."
        )

    return (
        f"{clean_summary}\n\n"
        f"{expanded_section}\n\n"
        f"**[Revision Summary]**: Reworked analysis to address feedback: *\"{feedback}\"*"
    )


async def revision_agent(state: ResearchState) -> dict[str, Any]:
    """Revise and improve the research summary incorporating human feedback.

    LangGraph Concept: Adaptive Feedback Loop
    - Reads `human_feedback` and current `summary`.
    - Actively performs targeted supplementary retrieval for the feedback topic.
    - Combines prior and new evidence.
    - Prompts LLM or executes intelligent heuristic rework strictly addressing the feedback.
    - Returns updated `summary`, newly gathered `search_results`, and resets `human_approved` to None.
    """
    question = state.get("question", "")
    summary = state.get("summary", "")
    feedback = state.get("human_feedback", "") or "Please improve and refine the research summary."
    existing_results = state.get("search_results", [])

    logger.info("[GRAPH] Starting revision")
    logger.info(f"[Revision] Applying feedback to summary: '{feedback}'")

    # Step 1: Execute supplementary retrieval targeted to the reviewer's feedback
    new_results = await perform_supplementary_retrieval(question, feedback)
    all_search_results = merge_search_results(existing_results, new_results)

    # Step 2: Format evidence clearly distinguishing feedback evidence from original evidence
    formatted_docs = []
    if new_results:
        formatted_docs.append("=== TARGETED EVIDENCE RETRIEVED SPECIFICALLY FOR HUMAN FEEDBACK ===")
        for idx, doc in enumerate(new_results, 1):
            source = doc.get("source", "unknown").upper()
            title = doc.get("title", "Untitled")
            url = doc.get("url", "No URL")
            snippet = doc.get("content", "").strip()[:800]
            formatted_docs.append(f"[{idx}] Source: {source} | Title: {title} | Link: {url}\nExcerpt: {snippet}\n")

    valid_existing = [
        r for r in existing_results
        if r.get("content") and not r.get("title", "").lower().startswith("search error")
    ]
    if valid_existing:
        formatted_docs.append("=== BACKGROUND RESEARCH EVIDENCE ===")
        offset = len(new_results)
        for idx, doc in enumerate(valid_existing[:6], offset + 1):
            source = doc.get("source", "unknown").upper()
            title = doc.get("title", "Untitled")
            url = doc.get("url", "No URL")
            snippet = doc.get("content", "").strip()[:600]
            formatted_docs.append(f"[{idx}] Source: {source} | Title: {title} | Link: {url}\nExcerpt: {snippet}\n")

    evidence_text = "\n".join(formatted_docs)

    llm = get_llm()
    revised_summary = ""

    if llm is not None:
        system_prompt = (
            "You are an expert research editor and synthesizer. Your objective is to thoroughly rework, "
            "expand, and refine the research summary to directly address the human reviewer's feedback.\n\n"
            "CRITICAL INSTRUCTIONS:\n"
            "1. Directly and thoroughly address the human reviewer's feedback for the user's specific topic.\n"
            "2. Comprehensively integrate the requested topic, angle, or details specified in the human feedback into the research summary.\n"
            "3. If the reviewer requested specific information (such as policy stances, aid, events, actions, or mechanisms), "
            "provide substantive factual details derived from the newly retrieved evidence.\n"
            "4. Never tell the user to search elsewhere, never tell the user to search Wikipedia, and never state that information is missing. "
            "Formulate a complete, authoritative, and well-structured research report.\n"
            "5. If the feedback asks for examples or use cases, generate concrete real-world scenarios illustrating the topic.\n"
            "6. If the feedback asks for a shorter or concise answer, condense the content into a high-impact summary.\n"
            "7. Seamlessly integrate the background context from the original summary with the new findings.\n"
            "8. Output the complete revised research summary in markdown."
        )
        user_prompt = (
            f"Original Question: {question}\n\n"
            f"Human Reviewer Feedback to Fulfill:\n\"{feedback}\"\n\n"
            f"Retrieved Evidence:\n{evidence_text}\n\n"
            f"Current Summary (to be updated):\n{summary}\n\n"
            f"Produce the updated, complete research summary strictly incorporating the feedback."
        )
        try:
            res = await asyncio.wait_for(
                llm.ainvoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]),
                timeout=25.0,
            )
            content = res.content if hasattr(res, "content") else str(res)
            # Guard against empty or refusenik output
            if content and len(content.strip()) > 50 and not ("search on wikipedia" in content.lower() and len(content.strip()) < 200):
                revised_summary = content.strip()
            else:
                logger.warning("[Revision] LLM output unaligned or incomplete. Using heuristic rework.")
        except asyncio.TimeoutError:
            logger.warning("[Revision] LLM revision call timed out after 25s. Using instant heuristic rework.")
        except Exception as exc:
            logger.warning(f"[Revision] LLM revision call failed: {exc}. Using heuristic fallback.")

    if not revised_summary:
        revised_summary = heuristic_rework_summary(
            question,
            summary,
            feedback,
            all_search_results,
            new_results=new_results,
        )

    logger.info("[Revision] Summary revision completed.")
    return {
        "summary": revised_summary,
        "search_results": new_results,
        "human_approved": None,
    }


