"""Specialized Agent implementations for the Multi-Agent Research Assistant.

LangGraph Concept: Specialized Agent Nodes
------------------------------------------
In LangGraph, each agent is a Python function (node) that receives the current
`ResearchState` and returns a dictionary of state updates.

Rather than relying on a single monolithic LLM call:
1. Planning Agent decomposes the user's question into targeted sub-tasks.
2. DuckDuckGo Agent queries live web search tools via MCP.
3. Wikipedia Agent queries encyclopedic tools via MCP in parallel.
4. Summarizer Agent synthesizes and contrasts evidence across sources.
5. Final Answer Agent compiles a cited, verified final response.
"""

import json
import logging
import os
import re
from typing import Any

from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import BaseTool

from app.state import ResearchState
from app.tools import load_research_tools

logger = logging.getLogger("research_assistant.agents")


# ---------------------------------------------------------------------------
# Structured Output Schemas
# ---------------------------------------------------------------------------
class ResearchPlanOutput(BaseModel):
    """Structured research plan generated by the Planning Agent."""

    research_plan: list[str] = Field(
        description="A list of 3 to 5 specific, distinct search tasks or queries to research the question."
    )


# ---------------------------------------------------------------------------
# LLM Provider Factory
# ---------------------------------------------------------------------------
def get_llm():
    """Initialize and return the configured LangChain ChatModel.

    Checks `LLM_PROVIDER` in environment:
    - 'gemini' (default): Uses `langchain-google-genai` ChatGoogleGenerativeAI.
    - 'groq': Uses ChatGroq if installed and configured.
    - 'mistral': Uses ChatMistralAI if installed and configured.
    - If no valid API key is present or LLM_PROVIDER is 'mock', returns None
      to enable graceful heuristic fallback for offline testing.
    """
    provider = os.getenv("LLM_PROVIDER", "gemini").lower()
    google_key = os.getenv("GOOGLE_API_KEY", "")

    if provider == "gemini":
        if not google_key or "your_api_key_here" in google_key:
            logger.info("No active GOOGLE_API_KEY found; operating in graceful mock/offline mode.")
            return None
        from langchain_google_genai import ChatGoogleGenerativeAI

        model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
        return ChatGoogleGenerativeAI(
            model=model_name,
            google_api_key=google_key,
            temperature=0.2,
        )

    if provider == "groq":
        groq_key = os.getenv("GROQ_API_KEY", "")
        if not groq_key or "your_api_key_here" in groq_key:
            return None
        try:
            from langchain_groq import ChatGroq

            return ChatGroq(
                model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
                api_key=groq_key,
                temperature=0.2,
            )
        except ImportError:
            logger.warning("langchain-groq not installed. Falling back to offline mode.")
            return None

    return None


# ---------------------------------------------------------------------------
# 1. Planning Agent
# ---------------------------------------------------------------------------
async def planning_agent(state: ResearchState) -> dict[str, Any]:
    """Analyze the user question and produce a structured research plan.

    LangGraph Concept: Planning Node
    - Receives `question` from state.
    - Uses structured LLM output to produce 3-5 specific sub-queries.
    - Updates `state['research_plan']`.
    """
    question = state.get("question", "").strip()
    logger.info(f"[Planner] Creating research plan for: '{question}'")

    llm = get_llm()
    plan: list[str] = []

    if llm is not None:
        try:
            # Try structured output first
            structured_llm = llm.with_structured_output(ResearchPlanOutput)
            prompt = (
                f"You are an expert research planner. Deconstruct the following question "
                f"into 3 to 4 distinct, highly focused research tasks or search queries that "
                f"cover definitions, core mechanisms, benefits/trade-offs, and practical comparisons.\n\n"
                f"Question: {question}"
            )
            result = await structured_llm.ainvoke(prompt)
            if result and getattr(result, "research_plan", None):
                plan = [p.strip() for p in result.research_plan if p.strip()]
        except Exception as exc:
            logger.warning(f"[Planner] Structured LLM call failed: {exc}. Trying raw completion.")
            try:
                raw_res = await llm.ainvoke(
                    f"Create a 3-point research plan for: '{question}'. "
                    f"Return ONLY a JSON list of strings, for example: [\"query 1\", \"query 2\", \"query 3\"]"
                )
                content = raw_res.content if hasattr(raw_res, "content") else str(raw_res)
                # Extract json list
                match = re.search(r"\[.*\]", content, re.DOTALL)
                if match:
                    plan = json.loads(match.group(0))
            except Exception as raw_exc:
                logger.warning(f"[Planner] Raw completion also failed: {raw_exc}.")

    # Deterministic fallback plan if LLM not configured or offline
    if not plan:
        plan = [
            f"Overview and definition of {question}",
            f"Key features and technical architecture of {question}",
            f"Advantages, limitations, and use cases of {question}",
        ]

    logger.info(f"[Planner] Generated {len(plan)} research tasks: {plan}")
    return {"research_plan": plan}


def parse_mcp_content(raw_value: Any, query: str) -> list[dict[str, Any]]:
    """Parse MCP tool result into structured dictionary records."""
    records: list[dict[str, Any]] = []

    def _process_text(text: str):
        try:
            parsed = json.loads(text)
            if isinstance(parsed, list):
                for p in parsed:
                    if isinstance(p, dict):
                        records.append({"query": query, **p})
                    else:
                        records.append({"query": query, "content": str(p)})
            elif isinstance(parsed, dict):
                records.append({"query": query, **parsed})
            else:
                records.append({"query": query, "content": str(parsed)})
        except Exception:
            records.append({"query": query, "content": text})

    if isinstance(raw_value, list):
        for item in raw_value:
            if isinstance(item, dict):
                if "text" in item:
                    _process_text(item["text"])
                else:
                    records.append({"query": query, **item})
            elif hasattr(item, "text"):
                _process_text(getattr(item, "text", ""))
            elif isinstance(item, str):
                _process_text(item)
    elif isinstance(raw_value, dict):
        if "text" in raw_value:
            _process_text(raw_value["text"])
        else:
            records.append({"query": query, **raw_value})
    elif isinstance(raw_value, str):
        _process_text(raw_value)

    return records


# ---------------------------------------------------------------------------
# 2. DuckDuckGo Retrieval Agent
# ---------------------------------------------------------------------------
async def duckduckgo_retrieval_agent(state: ResearchState) -> dict[str, Any]:
    """Execute live web searches using DuckDuckGo MCP tool based on research plan.

    LangGraph Concept: Specialized Retrieval Node (Branch 1)
    - Reads `research_plan` and `retry_count`.
    - Selects targeted web search queries.
    - Invokes the MCP tool asynchronously.
    - Normalizes results into consistent schema: {source, query, title, url, content}.
    """
    plan = state.get("research_plan", [])
    question = state.get("question", "")
    retry_count = state.get("retry_count", 0)

    logger.info(f"[DuckDuckGo] Searching live web (attempt {retry_count + 1})...")

    # Select queries: adapt if this is a retry attempt
    queries_to_run: list[str] = []
    if retry_count > 0:
        # Broaden search on retry
        queries_to_run = [f"{question} overview summary", f"{question} documentation"]
    elif plan:
        # Pick top 2 queries from plan
        queries_to_run = plan[:2]
    else:
        queries_to_run = [question]

    raw_items: list[dict[str, Any]] = []
    errors: list[str] = []

    try:
        tools = await load_research_tools()
        ddg_tool: BaseTool | None = tools.get("duckduckgo")

        if ddg_tool is not None:
            for q in queries_to_run:
                try:
                    logger.debug(f"[DuckDuckGo] Invoking MCP tool for query: '{q}'")
                    result = await ddg_tool.ainvoke({"query": q, "max_results": 3})
                    parsed_records = parse_mcp_content(result, q)
                    raw_items.extend(parsed_records)
                except Exception as tool_exc:
                    err_msg = f"DuckDuckGo MCP tool query '{q}' failed: {tool_exc}"
                    logger.warning(f"[DuckDuckGo] {err_msg}")
                    errors.append(err_msg)
        else:
            errors.append("DuckDuckGo MCP tool was not found in loaded tools.")
    except Exception as mcp_exc:
        err_msg = f"Failed to connect to DuckDuckGo MCP server: {mcp_exc}"
        logger.error(f"[DuckDuckGo] {err_msg}")
        errors.append(err_msg)

    # Normalize results into expected schema
    normalized_results: list[dict[str, str]] = []
    for item in raw_items:
        title = item.get("title") or "Web Search Result"
        content = item.get("content") or item.get("body") or ""
        url = item.get("url") or item.get("href") or ""
        q = item.get("query") or question

        if content.strip():
            normalized_results.append(
                {
                    "source": "duckduckgo",
                    "query": q,
                    "title": title,
                    "url": url,
                    "content": content,
                }
            )

    logger.info(f"[DuckDuckGo] Retrieved {len(normalized_results)} valid records.")
    return {
        "duckduckgo_results": normalized_results,
        "search_results": normalized_results,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# 3. Wikipedia Retrieval Agent
# ---------------------------------------------------------------------------
async def wikipedia_retrieval_agent(state: ResearchState) -> dict[str, Any]:
    """Retrieve encyclopedia articles using Wikipedia MCP tool based on research plan.

    LangGraph Concept: Specialized Retrieval Node (Branch 2)
    - Runs in parallel with DuckDuckGo agent.
    - Queries Wikipedia MCP tool for conceptual / background articles.
    - Normalizes results into consistent schema: {source, query, title, url, content}.
    """
    plan = state.get("research_plan", [])
    question = state.get("question", "")
    retry_count = state.get("retry_count", 0)

    logger.info(f"[Wikipedia] Searching encyclopedia (attempt {retry_count + 1})...")

    # Select queries: adapt on retry or extract core concept
    queries_to_run: list[str] = []
    if retry_count > 0:
        # Simplify to base keywords on retry
        cleaned = re.sub(r"(?i)\b(what|how|why|is|are|the|of|for|in|to)\b", "", question).strip()
        queries_to_run = [cleaned if cleaned else question]
    elif len(plan) >= 2:
        # Pick 2 complementary queries from plan
        queries_to_run = [plan[0], plan[-1]]
    elif plan:
        queries_to_run = [plan[0]]
    else:
        queries_to_run = [question]

    raw_items: list[dict[str, Any]] = []
    errors: list[str] = []

    try:
        tools = await load_research_tools()
        wiki_tool: BaseTool | None = tools.get("wikipedia")

        if wiki_tool is not None:
            for q in queries_to_run:
                try:
                    logger.debug(f"[Wikipedia] Invoking MCP tool for query: '{q}'")
                    result = await wiki_tool.ainvoke({"query": q, "max_results": 2})
                    parsed_records = parse_mcp_content(result, q)
                    raw_items.extend(parsed_records)
                except Exception as tool_exc:
                    err_msg = f"Wikipedia MCP tool query '{q}' failed: {tool_exc}"
                    logger.warning(f"[Wikipedia] {err_msg}")
                    errors.append(err_msg)
        else:
            errors.append("Wikipedia MCP tool was not found in loaded tools.")
    except Exception as mcp_exc:
        err_msg = f"Failed to connect to Wikipedia MCP server: {mcp_exc}"
        logger.error(f"[Wikipedia] {err_msg}")
        errors.append(err_msg)

    # Normalize results into expected schema
    normalized_results: list[dict[str, str]] = []
    for item in raw_items:
        title = item.get("title") or "Wikipedia Article"
        content = item.get("content") or item.get("summary") or ""
        url = item.get("url") or ""
        q = item.get("query") or question

        if content.strip():
            normalized_results.append(
                {
                    "source": "wikipedia",
                    "query": q,
                    "title": title,
                    "url": url,
                    "content": content,
                }
            )

    logger.info(f"[Wikipedia] Retrieved {len(normalized_results)} valid records.")
    return {
        "wikipedia_results": normalized_results,
        "search_results": normalized_results,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# 4. Evaluation & Retry Node (Fan-in Join Point)
# ---------------------------------------------------------------------------
async def evaluate_retrieval(state: ResearchState) -> dict[str, Any]:
    """Examine retrieved results and manage retry state if needed.

    LangGraph Concept: Fan-in Barrier & Conditional Transition
    - Both parallel branches (DuckDuckGo and Wikipedia) merge into this node.
    - Determines if useful content has been collected.
    - If empty and retry budget remains, increments `retry_count`.
    """
    search_results = state.get("search_results", [])
    retry_count = state.get("retry_count", 0)

    # Filter out empty or error results to determine true content availability
    valid_results = [
        r for r in search_results
        if r.get("content") and not r.get("title", "").lower().startswith("search error")
    ]

    has_results = len(valid_results) > 0
    max_retries = int(os.getenv("MAX_RETRIES", "2"))

    if not has_results and retry_count < max_retries:
        next_retry = retry_count + 1
        logger.warning(
            f"[Retry Check] No search results found. Scheduling retry {next_retry}/{max_retries}..."
        )
        return {"retry_count": next_retry}

    if not has_results and retry_count >= max_retries:
        logger.warning(
            f"[Retry Check] Maximum retry limit ({max_retries}) reached. Continuing with available context."
        )

    logger.info(f"[Retry Check] Found {len(valid_results)} usable records. Proceeding to summarizer.")
    return {}


# ---------------------------------------------------------------------------
# 5. Summarization Agent
# ---------------------------------------------------------------------------
async def summarization_agent(state: ResearchState) -> dict[str, Any]:
    """Consolidate research findings, deduplicate, and identify key facts.

    LangGraph Concept: Synthesis Node
    - Combines information from DuckDuckGo (live web) and Wikipedia (encyclopedic).
    - Avoids hallucination by grounding only on retrieved results.
    - Stores synthesized summary in `state['summary']`.
    """
    question = state.get("question", "")
    research_plan = state.get("research_plan", [])
    search_results = state.get("search_results", [])

    logger.info("[Summarizer] Combining research and synthesizing summary...")

    valid_results = [
        r for r in search_results
        if r.get("content") and not r.get("title", "").lower().startswith("search error")
    ]

    if not valid_results:
        fallback_summary = (
            f"No live research results were retrieved for '{question}'. "
            f"The search queries in the research plan ({', '.join(research_plan)}) "
            f"did not return accessible documents through DuckDuckGo or Wikipedia."
        )
        return {"summary": fallback_summary}

    # Format documents for synthesis
    formatted_docs: list[str] = []
    for idx, doc in enumerate(valid_results, 1):
        source = doc.get("source", "unknown").upper()
        title = doc.get("title", "Untitled")
        url = doc.get("url", "No URL")
        snippet = doc.get("content", "").strip()[:800]
        formatted_docs.append(
            f"[{idx}] Source: {source} | Title: {title} | Link: {url}\nExcerpt: {snippet}\n"
        )
    evidence_text = "\n".join(formatted_docs)

    llm = get_llm()
    summary_text = ""

    if llm is not None:
        system_prompt = (
            "You are a meticulous research analyst. Your job is to summarize retrieved research findings.\n"
            "Rules:\n"
            "1. Combine information from DuckDuckGo and Wikipedia.\n"
            "2. Eliminate duplicate facts and contradictions.\n"
            "3. Clearly cite which facts come from DuckDuckGo (web) vs Wikipedia.\n"
            "4. Do NOT hallucinate or extrapolate facts not present in the evidence.\n"
            "5. Keep the summary structured and concise."
        )
        user_prompt = (
            f"Question: {question}\n\n"
            f"Research Plan Tasks: {json.dumps(research_plan)}\n\n"
            f"Retrieved Evidence:\n{evidence_text}\n\n"
            f"Produce a comprehensive synthesis and summary."
        )
        try:
            res = await llm.ainvoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
            summary_text = res.content if hasattr(res, "content") else str(res)
        except Exception as exc:
            logger.warning(f"[Summarizer] LLM invocation failed: {exc}. Using heuristic summary.")

    # Fallback heuristic summarization if LLM is offline or errored
    if not summary_text:
        ddg_count = sum(1 for r in valid_results if r.get("source") == "duckduckgo")
        wiki_count = sum(1 for r in valid_results if r.get("source") == "wikipedia")
        highlights = [
            f"- **{r.get('title')}** ({r.get('source')}): {r.get('content', '')[:180]}..."
            for r in valid_results[:4]
        ]
        summary_text = (
            f"### Research Synthesis for: '{question}'\n\n"
            f"Synthesized evidence from {ddg_count} DuckDuckGo web results and {wiki_count} Wikipedia articles.\n\n"
            f"**Key Findings Identified:**\n"
            + "\n".join(highlights)
        )

    logger.info("[Summarizer] Research summary generated successfully.")
    return {"summary": summary_text}


# ---------------------------------------------------------------------------
# 6. Final Answer Agent
# ---------------------------------------------------------------------------
async def final_answer_agent(state: ResearchState) -> dict[str, Any]:
    """Generate user-facing answer with Answer, Key Findings, and Sources.

    LangGraph Concept: Final Presentation Node
    - Receives `summary` and `search_results`.
    - Answers only from research gathered by prior nodes.
    - Formats output with strict sections: Answer, Key Findings, Sources.
    """
    question = state.get("question", "")
    summary = state.get("summary", "")
    search_results = state.get("search_results", [])

    logger.info("[Final Answer] Generating response with sources...")

    # Extract distinct source URLs and titles
    distinct_sources: list[tuple[str, str, str]] = []
    seen_urls: set[str] = set()
    for r in search_results:
        url = r.get("url", "").strip()
        title = r.get("title", "").strip()
        source = r.get("source", "").capitalize()
        if url and url not in seen_urls and not title.lower().startswith("search error"):
            seen_urls.add(url)
            distinct_sources.append((source, title, url))

    llm = get_llm()
    answer_text = ""

    if llm is not None:
        sources_list_str = "\n".join(f"- [{title}]({url}) ({source})" for source, title, url in distinct_sources)
        system_prompt = (
            "You are a professional research assistant. Formulate the final answer for the user.\n"
            "Structure your response strictly as follows:\n\n"
            "## Answer\n"
            "<A clear, comprehensive direct answer to the user's question, grounded in the research summary.>\n\n"
            "## Key Findings\n"
            "<Bullet points highlighting 3-5 critical takeaways, advantages, or trade-offs.>\n\n"
            "## Sources\n"
            "<List of markdown links to all sources referenced with their titles.>\n\n"
            "Never invent facts or references not provided in the summary."
        )
        user_prompt = (
            f"User Question: {question}\n\n"
            f"Research Summary:\n{summary}\n\n"
            f"Available Sources:\n{sources_list_str}"
        )
        try:
            res = await llm.ainvoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
            answer_text = res.content if hasattr(res, "content") else str(res)
        except Exception as exc:
            logger.warning(f"[Final Answer] LLM call failed: {exc}. Using template.")

    # Fallback template formatting
    if not answer_text:
        source_lines = [
            f"- [{title}]({url}) ({source})" for source, title, url in distinct_sources
        ] or ["- No external source links accessible."]

        answer_text = (
            f"## Answer\n"
            f"Based on gathered research for '{question}':\n\n"
            f"{summary}\n\n"
            f"## Key Findings\n"
            f"- Information was gathered independently from live web search and encyclopedic records.\n"
            f"- The synthesis consolidates definitions, core components, and practical context.\n"
            f"- Further domain-specific verification may be conducted via the sources below.\n\n"
            f"## Sources\n"
            + "\n".join(source_lines)
        )

    logger.info("[Final Answer] Final response compiled.")
    return {"final_answer": answer_text}
