"""Shared state definition for the LangGraph Multi-Agent Research Assistant.

LangGraph Concept: State Management
------------------------------------
In LangGraph, state is passed between nodes as an immutable dictionary.
Each node receives the current state and returns a dictionary with updates to apply.

When multiple nodes run in parallel (such as DuckDuckGo and Wikipedia retrieval agents),
they may write to the state at the exact same time. If two parallel nodes attempt to write
to a standard key without a reducer, LangGraph raises an `InvalidUpdateError`.

To support concurrent branch writes and clean aggregation, fields can be wrapped in
`typing.Annotated` with an accumulator function (reducer), such as `operator.add` or
a custom deduplicating merge function like `merge_search_results`.
"""

import operator
from typing import Annotated, TypedDict


def merge_search_results(
    existing: list[dict], new_items: list[dict]
) -> list[dict]:
    """Reducer function to merge and deduplicate search results from parallel agents.

    Parameters:
        existing: List of already recorded search result dictionaries.
        new_items: Newly retrieved search result dictionaries from an agent.

    Returns:
        A combined list preserving original order and eliminating duplicates based on
        source, URL, and title.
    """
    if not existing:
        existing = []
    if not new_items:
        return list(existing)

    seen = {
        (
            item.get("source", ""),
            item.get("url", ""),
            item.get("title", "").strip().lower(),
        )
        for item in existing
    }

    merged = list(existing)
    for item in new_items:
        key = (
            item.get("source", ""),
            item.get("url", ""),
            item.get("title", "").strip().lower(),
        )
        if key not in seen:
            seen.add(key)
            merged.append(item)

    return merged


class ResearchState(TypedDict):
    """The complete shared state dictionary for the multi-agent research graph.

    Fields:
        question:
            The original research question provided by the user.

        research_plan:
            A list of 3-5 specific, focused sub-queries or tasks generated by the
            Planning Agent to guide information retrieval.

        duckduckgo_results:
            Raw search result records collected by the DuckDuckGo Retrieval Agent.
            Uses `operator.add` to accumulate results across initial search and retries.

        wikipedia_results:
            Raw search result records collected by the Wikipedia Retrieval Agent.
            Uses `operator.add` to accumulate results across initial search and retries.

        search_results:
            The consolidated, deduplicated collection of all normalized search results
            from all retrieval agents. Uses `merge_search_results` reducer to support
            concurrent writes from parallel branches.

        summary:
            A coherent, comprehensive synthesis of all retrieved information produced
            by the Summarization Agent, citing facts and contrasting sources.

        final_answer:
            The final user-facing response generated by the Final Answer Agent,
            structured into Direct Answer, Key Findings, and Sources.

        retry_count:
            The number of retry cycles completed when initial retrieval produced
            insufficient information. Evaluated by conditional routing edges.

        errors:
            A cumulative list of non-fatal warnings or error messages encountered
            during tool execution or LLM generation. Uses `operator.add`.

        human_approved:
            Boolean flag indicating whether the human reviewer approved the research
            summary, or None if awaiting review.

        human_feedback:
            Optional feedback or revision instructions provided by the human reviewer
            upon rejection, or None.
    """

    question: str
    research_plan: list[str]
    duckduckgo_results: Annotated[list[dict], operator.add]
    wikipedia_results: Annotated[list[dict], operator.add]
    search_results: Annotated[list[dict], merge_search_results]
    summary: str
    final_answer: str
    retry_count: int
    errors: Annotated[list[str], operator.add]
    human_approved: bool | None
    human_feedback: str | None


def create_initial_state(question: str) -> ResearchState:
    """Helper to initialize a clean ResearchState dictionary for a given question.

    Args:
        question: The user-submitted research inquiry.

    Returns:
        A populated ResearchState dictionary with empty defaults for accumulators.
    """
    return {
        "question": question,
        "research_plan": [],
        "duckduckgo_results": [],
        "wikipedia_results": [],
        "search_results": [],
        "summary": "",
        "final_answer": "",
        "retry_count": 0,
        "errors": [],
        "human_approved": None,
        "human_feedback": None,
    }

